[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "insurance"
version = "0.0.0"
description = "Insurance API demo"
authors = [{name = "Alex Wong"}]

[tool.setuptools.packages.find]
where = ["."]
include = ["insurance*"]